GET http://localhost:5000/
Accept: application/json

###

GET http://localhost:5000/1
Accept: application/json

###

POST http://localhost:5000/
Content-Type: application/json

{
  "Joke": "John Doe",
  "Punchline": "Per"
}