GET http://localhost:5000/
Accept: application/json

###

GET http://localhost:5000/1
Accept: application/json

###

POST http://localhost:5000/
Content-Type: application/json

{
  "Opening": "I got fired from the transmission factory today.",
  "Punchline": "Apparently, I was not putting in enough shifts."
}